
[general]

profile_img_url= https://raw.githubusercontent.com/KOP-XIAO/QuantumultX/master/img/dragonball/1.PNG

network_check_url = http://www.bing.com

server_check_url = http://www.gstatic.com/generate_204

server_check_timeout = 3000

# geo_location_checker = http://ip-api.com/json/?lang=zh-CN,https://cdn.jsdelivr.net/gh/KOP-XIAO/QuantumultX@master/Scripts/IP_API.js

resource_parser_url = https://cdn.jsdelivr.net/gh/KOP-XIAO/QuantumultX@master/Scripts/resource-parser.js

dns_exclusion_list = *.lan, cable.auth.com, *.msftconnecttest.com, *.msftncsi.com, network-test.debian.org, detectportal.firefox.com, resolver1.opendns.com, *.srv.nintendo.net, *.stun.playstation.net, xbox.*.microsoft.com, *.xboxlive.com, stun.*, *.qq.com, localhost.*.qq.com, *.logon.battlenet.com.cn, *.logon.battle.net, *.blzstatic.cn, *.cmpassport.com, id6.me, open.e.189.cn, mdn.open.wo.cn, auth.wosms.cn, *.jegotrip.com.cn, *.icitymobile.mobi, *.pingan.com.cn, *.cmbchina.com, *?miwifi.com, pool.ntp.org, *.pool.ntp.org, ntp.*.com, time.*.com, ntp?.*.com, time?.*.com, time.*.gov, time.*.edu.cn, *.ntp.org.cn, time.*.apple.com, PDC._msDCS.*.*, DC._msDCS.*.*, GC._msDCS.*.*

excluded_routes = 192.168.0.0/16, 172.16.0.0/12, 100.64.0.0/10, 10.0.0.0/8, 239.255.255.250/32


[dns]

server = 119.29.29.29
server = 182.254.116.116
server = 223.5.5.5
server = 223.6.6.6
server = 119.28.28.28


[policy]

url-latency-benchmark=🇺🇸 United State, server-tag-regex=^(?=.*((?i)🇺🇸|美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|(\b(US|United States)\b)))(?!.*((?i)回国|校园|游戏|🎮|(\b(GAME)\b))).*$, check-interval=600, tolerance=0, alive-checking=false, img-url=https://raw.githubusercontent.com/crossutility/Quantumult-X/master/icon-samples/us.PNG
static=BackCN, direct, proxy, reject, img-url=https://raw.githubusercontent.com/crossutility/Quantumult-X/master/icon-samples/cn.PNG



[server_local]

[server_remote]
American.snippet, tag=🇺🇸us-node, update-interval=172800, opt-parser=true, enabled=true


[filter_local]

ip-cidr, 10.0.0.0/8, direct
ip-cidr, 127.0.0.0/8, direct
ip-cidr, 172.16.0.0/12, direct
ip-cidr, 192.168.0.0/16, direct
ip-cidr, 224.0.0.0/24, direct
final, direct

[filter_remote]

https://jkoch14.me/qx/rules/LocalAreaNetwork.list, tag=LocaAreaNetwork, force-policy=direct, update-interval=86400, opt-parser=false, enabled=true
https://jkoch14.me/qx/rules/BanEasyList.list, tag=BanEasyList, force-policy=reject, update-interval=172800, opt-parser=false, enabled=true
https://jkoch14.me/qx/rules/Microsoft.list, tag=Microsoft, force-policy=𝗣𝗥𝗢𝗫𝗬, update-interval=172800, opt-parser=true, enabled=true
https://jkoch14.me/qx/rules/ChinaDomain.list, tag=ChinaDomain, force-policy=direct, update-interval=172800, opt-parser=false, enabled=true
https://jkoch14.me/qx/rules/Apple.list, tag=Apple, force-policy=direct, update-interval=86400, opt-parser=false, enabled=true
https://jkoch14.me/qx/rules/ProxyLite.list, tag=ProxyLite, force-policy=𝗣𝗥𝗢𝗫𝗬, update-interval=86400, opt-parser=true, enabled=true




[rewrite_local]

[rewrite_remote]


[task_local]
# 流媒体查询脚本
event-interaction https://cdn.jsdelivr.net/gh/KOP-XIAO/QuantumultX@master/Scripts/streaming-ui-check.js, tag = 流媒体 - 解锁查询，img-url=checkmark.seal.system, enabled=true

[http_backend]

[mitm]
